<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function sj_core_help($path, $arg) {
  switch ($path) {
    case "admin/help#sj_core":
      return '<p>Manage private projects</p>';
      break;
  }
} 

// project config
module_load_include ('config', 'sj_core', 'sj_db_tables');

// drupal hooks
sj_core_load_all_hooks('sj_core');

// api
module_load_include ('class', 'sj_core', 'api/sjColorSet');
module_load_include ('class', 'sj_core', 'api/sjUser');

// custom global libraries
module_load_include ('inc', 'sj_core', 'sj_core_lib');


function sj_core_load_all_hooks ($module) {
	$hooks = scandir(drupal_get_path('module', $module).'/hooks');
	foreach ($hooks as $hook) {
		if ($hook === '.' || $hook === '..') continue;
		$tokens = explode('.', $hook);
		module_load_include ($tokens[1], $module, 'hooks/'.$tokens[0]);
	}
}



