<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function sj_core_help($path, $arg) {
  switch ($path) {
    case "admin/help#sj_core":
      return '<p>Manage private projects</p>';
      break;
  }
} 

// project config
module_load_include ('config', 'sj_core', 'sj_db_tables');

// drupal hooks
module_load_include ('inc', 'sj_core', 'hooks/permission');
module_load_include ('inc', 'sj_core', 'hooks/menu');
module_load_include ('inc', 'sj_core', 'hooks/entity_info');

// api
module_load_include ('class', 'sj_core', 'api/sjColorSet');
module_load_include ('class', 'sj_core', 'api/sjUser');

// custom global libraries
module_load_include ('inc', 'sj_core', 'sj_core_lib');



/**
 * Implements hook_block_info().
 */
function sj_core_block_info() {
  $blocks['sj_core_personas'] = array(
    // The name that will appear in the block list.
    'info' => t('SuoJure: Personas'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sj_core_block_view($delta = '') {
  switch ($delta) {
  case 'sj_core_personas':
    module_load_include ('inc', 'sj_core', 'blocks/personas');
    
	$block['subject'] = t('SuoJure: Personas');
    $block['content'] = sj_core_personas_block();
  }

  return $block;
}


