<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function sj_core_help($path, $arg) {
  switch ($path) {
    case "admin/help#sj_core":
      return '<p>Manage private projects</p>';
      break;
  }
} 

// project config
module_load_include ('config', 'sj_core', 'sj_db_tables');

// drupal hooks
module_load_include ('inc', 'sj_core', 'hooks/permission');
module_load_include ('inc', 'sj_core', 'hooks/menu');

// custom global libraries
module_load_include ('inc', 'sj_core', 'sj_core_lib');





